# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: openjdk:8-jdk
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: tp_devops
          POSTGRES_PASSWORD: tp_devops
          POSTGRES_DB: tp_devops


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - env:
          DOCKER_HUB: ${{secrets.DOCKER_HUB}}
          DOCKER_HUB_KEY: ${{secrets.DOCKER_HUB_KEY }}  
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shel
      - name: build the app
        run: ./gradlew assemble

      - name: check the app
        run: ./gradlew check -i -P database.url=postgres/tp_devops
        
      - name: docker image 
        run: ./gradlew docker
        
      - name: login docker
        run: docker login -u $DOCKER_HUB -p $DOCKER_HUB_KEY
      
      - name: push image
        run: docker push remisalmi/tp-devops:1.0.0
        
        
        
        
